### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by GIGer228** [GIGer228/Nora#3]
As with every discord bot users must be able to limit Nora's functionality on a server. There must be a clear defined list of rules/settings to configure Nora.
Following User-Stories are related:

- [ ] 1. List of commands and their functionalities.
- [ ] 2. Set a chat-channel.
- [ ] 3. Set a time limit between messages to listen to after that the conversation ends.
- [ ] 4. Set a list of trusted users to configure Nora.
